#tutorial de python

In [17]:
import numpy as np
a = 1.0
print( a, '\n')

b = np.array([1, 2, 3, 4], dtype=np.float64)
print(b, '\n')

1.0 

[1. 2. 3. 4.] 



In [13]:
u = np.ones(shape=(2,5), dtype=np.float64)
print(u, '\n')

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 



In [19]:
#matriz randomica
r = np.random.rand(3,4)
print(r, '\n')

[[0.67796701 0.40105583 0.90900311 0.59690136]
 [0.23716076 0.44193695 0.92302694 0.72173458]
 [0.12970375 0.32545772 0.9388903  0.63228364]] 



In [23]:
#numero uniformemente distribuidos
a = 2.5
b = 3.8
q = a + (b-a)*r
print(q)

[[3.38135711 3.02137258 3.68170404 3.27597177]
 [2.80830899 3.07451803 3.69993503 3.43825495]
 [2.66861487 2.92309503 3.72055739 3.32196873]]


In [26]:
#inteiro randomicos
ui = np.random.randint(4,8, size=(6,2), dtype=np.int32)
print(ui, '\n')

[[7 6]
 [6 5]
 [5 5]
 [6 6]
 [6 7]
 [5 7]] 



In [55]:
##Operações com matrizes e vetores
##aplic funçao em um array
C = np.random.randint(4,8, size=(6,2), dtype=np.int32)
Z = np.zeros(shape=(3,5), dtype=np.float64)
CZ = np.cos(Z)
print(CZ, '\n')

I = np.identity(4, dtype = np.float64)
EI = np.exp(I)
print(EI, '\n')

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[2.71828183 1.         1.         1.        ]
 [1.         2.71828183 1.         1.        ]
 [1.         1.         2.71828183 1.        ]
 [1.         1.         1.         2.71828183]] 



In [52]:
v1 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
v2 = np.array([2.0, 3.0, 4.0], dtype=np.float64)

#combinação linear
alpha = 0.4
beta = 0.6
v3 = alpha*v1 + beta*v2
print(v3, '\n')

#produto ponto a ponto
v4 = v1 * v2
print(v4, '\n')

#produto escalar
v4 = v1 @ v2
print(v4, '\n')

#seria o mesmo que
q = np.sum(v4)
print(q, '\n')

#produto metriz vetor
A = np.array(([1,2,3],[4,5,6]), dtype=np.float64)
x = np.array([10,20,30], dtype=np.float64)
y = A @ x
print(y, '\n')

[1.6 2.6 3.6] 

[ 2.  6. 12.] 

20.0 

20.0 

[140. 320.] 



In [58]:
#funções
#forma de uma matriz
print(C.shape)
print(C.shape[0]) #num linhas
print(C.shape[1]) #num colunas
def myFunc( A, B):

    ncA = A.shape[1]
    ncB = B.shape[0]
    if(ncA != ncB):
        raise Exception('Produto incompativel')

    return C

(6, 2)
6
2


In [63]:
m = 100
r = 50
n = 200
A = np.random.rand(m,r)
B = np.random.rand(r,n)
C = myFunc(A, B)


