# Rede BAM

In [1]:
func.ativacao <- function(v){

	v[v < 0] <- -1
	v[v > 0] <- +1
	v[v == 0] <- sample(c(+1,-1),size=1)

	return(v)

}

In [2]:
bam.armazena <- function(X,Y) {

	# Matriz para armazenar os pesos
	pesos <- matrix(rep(0,ncol(X)*ncol(Y)), ncol(X), ncol(Y))

	for (i in 1:nrow(X)) {
		pesos <- pesos + X[i,]%o%Y[i,] # %o% = Outer product
	}

	return(list(pesos = pesos))
}

In [3]:
bam.teste <- function(M,x){

	H.antigo <- 100
	variacao.H <- 1

	while(variacao.H > 0){

		# Em direcao a Y
		sx <- as.vector(x %*% M)
		sx <- func.ativacao(sx)

		# Entropia -> quanto menor, menos confusao (melhor)
		H <- -(x %*% M %*% sx)

		# Em direcao a X
		x <- as.vector(M %*% sx)
		x <- func.ativacao(x)

		# Variacao na Entropia
		variacao.H <- abs(H - H.antigo)
		H.antigo <- H

		cat("\nVariação na Entropia = ",variacao.H,"\n")
	}

	cat("Saida: ")
	cat(sx,"\n")
	cat("Entrada: ")
	cat(x,"\n")

}

In [4]:
# Exemplo - Armazenar letras A e C
X <- matrix(c(-1,1,-1, 1,-1,1, 1,1,1, 1,-1,1, 1,-1,1,
              -1,1,1, 1,-1,-1, 1,-1,-1, 1,-1,-1, -1,1,1), nrow=2, byrow=T)
Y <- matrix(c(-1,1, 1,1), nrow=2,byrow=T)

print(X)

print(Y)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]   -1    1   -1    1   -1    1    1    1    1     1    -1     1     1    -1
[2,]   -1    1    1    1   -1   -1    1   -1   -1     1    -1    -1    -1     1
     [,15]
[1,]     1
[2,]     1
     [,1] [,2]
[1,]   -1    1
[2,]    1    1


In [5]:
# Cria a matriz de pesos
bam <- bam.armazena(X,Y)

print(bam)

$pesos
      [,1] [,2]
 [1,]    0   -2
 [2,]    0    2
 [3,]    2    0
 [4,]    0    2
 [5,]    0   -2
 [6,]   -2    0
 [7,]    0    2
 [8,]   -2    0
 [9,]   -2    0
[10,]    0    2
[11,]    0   -2
[12,]   -2    0
[13,]   -2    0
[14,]    2    0
[15,]    0    2



In [6]:
# Testa nos próprios padrões de entrada
a <- X[1,]
b <- X[2,]
bam.teste(bam$pesos,a)
bam.teste(bam$pesos,b)


Variação na Entropia =  130 

Variação na Entropia =  0 
Saida: -1 1 
Entrada: -1 1 -1 1 -1 1 1 1 1 1 -1 1 1 -1 1 

Variação na Entropia =  130 

Variação na Entropia =  0 
Saida: 1 1 
Entrada: -1 1 1 1 -1 -1 1 -1 -1 1 -1 -1 -1 1 1 


In [7]:
# Faz variacoes nos padroes de entrada
a[1] <- 1
a[7] <- -1
#a[5] <- 1
a[13] <- -1
a[15] <- -1

b[2] <- -1
b[5] <- 1
b[10] <- -1

print(a)

print(b)

 [1]  1  1 -1  1 -1  1 -1  1  1  1 -1  1 -1 -1 -1
 [1] -1 -1  1  1  1 -1  1 -1 -1 -1 -1 -1 -1  1  1


In [8]:
bam.teste(bam$pesos,a)
bam.teste(bam$pesos,b)


Variação na Entropia =  114 

Variação na Entropia =  16 

Variação na Entropia =  0 
Saida: -1 1 
Entrada: -1 1 -1 1 -1 1 1 1 1 1 -1 1 1 -1 1 

Variação na Entropia =  118 

Variação na Entropia =  12 

Variação na Entropia =  0 
Saida: 1 1 
Entrada: -1 1 1 1 -1 -1 1 -1 -1 1 -1 -1 -1 1 1 
