# SEL635/SEL5724 - Visão Computacional Aplicada a Robótica



**Aluno:** Preencher com seu nome

**NUSP:** Preencher com seu número USP

Versão do documento: 1.1

# Lista 7 - Visão Estéreo - Parte D

O propósito deste exercício é implementar alguns dos métodos relacionados à visão estéreo.

## Preparação do ambiente e definição de funções de exercícios anteriores

In [ ]:
# Importar as bibliotecas que serão utilizadas
import numpy as np
import matplotlib.pyplot as plt
import math


Defina a seguir as funções implementadas em exercícios anteriores que serão utilizadas nessa Tarefa:

In [ ]:
def proj_perspectiva(Pc,f):
  (M,N) = np.shape(Pc) # recupera o tamanho da matriz (N linhas, M colunas)
  if(M!=3):
    print('Aviso: a matriz Pc usada como entrada não possui três linhas!')

  pc = np.zeros((3,N))  # Inicializa o vetor pc de dimensão 3xN com zeros

  # Encontra a projeção perspectiva dos pontos no plano da imagem em [mm]:
  ######
  # Coloque aqui o seu código para calcular a matriz pc



  ######

  return pc

In [ ]:
def camera_to_image(pc,sx,sy,ox,oy):
  (M,N) = np.shape(pc) # recupera o tamanho da matriz (N linhas, M colunas)
  if(M!=3):
    print('Aviso: a matriz pc usada como entrada não possui três linhas!')

  p_im = np.zeros((2,N))  # Inicializa o vetor p de dimensão 2xN com zeros

  # Converte as coordenadas dos pontos pc do sistema da câmera em [mm] para o sistema de coordenadas da imagem em [px]:
  ######
  # Coloque aqui o seu código para calcular a matriz p_im #####



  ######

  return p_im

In [ ]:
def calibration_pattern(n,d):
    Pw = np.zeros((3,3*n*n+7))
    Pw[:,0] = [0, 0, 0]
    Pw[:,1] = [n*d, 0, 0]
    Pw[:,2] = [0, n*d, 0]
    Pw[:,3]=[0, 0, n*d];
    Pw[:,4]=[n*d, n*d, 0];
    Pw[:,5]=[n*d, 0, n*d];
    Pw[:,6]=[0, n*d, n*d];

    for i in range(n):
        for j in range(n):
            Pw[:,n*i+j+7]= [d*j, d*i, 0]
            Pw[:,n*n + n*i+j+7]= [0, d*j, d*i];
            Pw[:,2*n*n + n*i+j+7]= [d*i, 0, d*j];

    return Pw

In [ ]:
def Rx(theta):
    theta = np.radians(theta)
    R = np.array([[1, 0, 0], [0, np.cos(theta), -np.sin(theta)], [0, np.sin(theta), np.cos(theta)]])
    return R
def Ry(theta):
    theta = np.radians(theta)
    R = np.array([[np.cos(theta), 0, np.sin(theta)], [0, 1, 0], [-np.sin(theta), 0, np.cos(theta)]])
    return R
def Rz(theta):
    theta = np.radians(theta)
    R = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
    return R
def Homogenea(R,t):
    t = t.reshape(-1, 1) #vetor de translação (formato de vetor coluna)
    H = np.concatenate((R,t),axis=1) #concatena na horizontal a matriz de rotação e vetor de translação
    temp_v = np.array([0,0,0,1]).reshape(1, -1) #ultima linha da matriz homogênia (formato de vetor linha)
    H = np.concatenate((H,temp_v),axis=0) #concatena na vertical a ultima linha da matriz de homografia
    return H

In [ ]:
def world_to_camera(Pw,Rwc,Twc):
    (M,N) = np.shape(Pw) # recupera o tamanho da matriz (M linhas, N colunas)

    # Coloque seu codigo aqui




    return Pc

In [ ]:
def world_to_image(Pw,Rwc,Twc,f,sx,sy,ox,oy):

    # Coloque seu codigo aqui


    return p_im

In [ ]:
def plot_image(p_im,size_x,size_y):
    plt.figure()
    plt.plot(p_im[0,4:],p_im[1,4:],'bo',mfc='none')
    plt.plot(p_im[0,0],p_im[1,0],'ko',mfc='none')
    plt.plot(p_im[0,1],p_im[1,1],'co',mfc='none')
    plt.plot(p_im[0,2],p_im[1,2],'ro',mfc='none')
    plt.plot(p_im[0,3],p_im[1,3],'go',mfc='none')
    plt.axis([0, size_x, size_y, 0])

In [ ]:
def calibrate_camera(Pw,p_im):



  return Rwc,Twc,fx,fy,ox,oy

In [ ]:
def skew_sym(v):
    return np.array([[0, -v[2], v[1]],
                     [v[2], 0, -v[0]],
                     [-v[1], v[0], 0]])

In [ ]:
# Adiciona uma linha igual 1 a todos os elementos da matriz pim.
# Dessa forma as coordenadas dos pontos na imagem ficam sendo representadas como coordenadas homogêneas
def image_to_homogeneous(pim):
  ncol = pim.shape[1]
  row_of_ones = np.ones(ncol)
  pim_h = np.vstack([pim, row_of_ones])
  return pim_h

In [ ]:
def essential_matrix(Rwc1,Twc1,Rwc2,Twc2):

    ## Implementar calculo da matriz essencial:




    return E

In [ ]:
def fundamental_matrix(Rwc1,Twc1,Rwc2,Twc2,fx,fy,ox,oy):
    E = essential_matrix(Rwc1,Twc1,Rwc2,Twc2)
    K = np.array([[-fx, 0, ox], [0, -fy, oy], [0, 0, 1]])

    ## Implementar calculo da matriz fundamental:
    # F =

    return F

In [ ]:
def reconstruction_3D(p_im1,p_im2,Rwc1,Twc1,Rwc2,Twc2,fx,fy,ox,oy):
    # Implementar um dos métodos de reconstrução 3D


    return Pc1_reconst

In [ ]:
def estimate_fundamental_matrix(p_im1,p_im2):
    ## Implementar a estimativa da matriz fundamental, normalize a matriz usando Fest[2,2]
    # F_est =


    # F_est = F_est/F_est[2,2]

    return F_est

In [ ]:
def estimate_essential_matrix(F_est,fx,fy,ox,oy):
    ## Implementar a estimativa da matriz essencial, normalize a matriz usando E_est[2,2]
    # E_est =


    # E_est = E_est/E_est[2,2]
    return E_est

In [ ]:
def estimate_reconstruct_3d(F_est,fx,fy,ox,oy):
    # Implementar um dos métodos de reconstrução 3D


    return Pw_reconst_est

## Imagens do Padrão de Calibração

Considere as duas câmeras e o padrão de calibração definidos e posicinados de acordo com as instruções da Tarefa 2.

Coloque a seguir a sequência de código utilizada ao final da Tarefa 2 para obter a imagem da câmera 1 e da câmera 2 do padrão de calibração.

In [ ]:
## Coloque seu código aqui para fazer cada um dos passos a seguir

# Definir o padrão de calibração:


# Coloque seu código aqui para gerar a imagem obtida pela câmera 1:

# Definir a câmera 1:


# TODO: Faça um print dos parâmetros intrínsecos e extrínsecos da camera 1



# Obter a imagem do padrão de calibração a partir da câmera 1:


# Coloque seu código aqui para gerar a imagem obtida pela câmera 2:

# Definir a câmera 2:



# TODO: Faça um print dos parâmetros intrínsecos e extrínsecos da camera 2


# Obter a imagem do padrão de calibração a partir da câmera 2:




## Parte A

In [ ]:
E = essential_matrix(Rwc1,Twc1,Rwc2,Twc2)
print(' E = ',E)
print('\n')
print('E_norm = ',E/E[2,2])
print('\n')

Pc1 = world_to_camera(Pw,Rwc1,Twc1)
Pc2 = world_to_camera(Pw,Rwc2,Twc2)

# Restrição epipolar para um dos pontos:
test = Pc1[:,1].T@E@Pc2[:,1]
print('Resultado da restrição epipolar para um ponto usando matriz essencial:')
print(test)


fx = f/sx
fy = f/sy
F = fundamental_matrix(Rwc1,Twc1,Rwc2,Twc2,fx,fy,ox,oy)
print(' F = ',F)
print('\n')
print(' F = ',F/F[2,2])
print('\n')

# Converte as coordenadas dos pontos na imagem para coordenadas homogêneas:
p_im1h = image_to_homogeneous(p_im1)
p_im2h = image_to_homogeneous(p_im2)

# Restrição epipolar para um dos pontos:
test = p_im1h[:,0].T@F@p_im2h[:,0]
print('Resultado da restrição epipolar para um ponto usando matriz fundamental:')
print(test)


Pc1_reconst = reconstruction_3D(p_im1,p_im2,Rwc1,Twc1,Rwc2,Twc2,fx,fy,ox,oy)
print(Pw_reconst)

# Calcular a distância Euclidiana entre Pc1_reconst e Pc1 dos 7 primeiros pontos::
# <completar_codigo>

# Imprimir a distância Euclidiana entre Pc1_reconst e Pc1 dos 7 primeiros pontos:
# <completar_codigo>

## Parte B

In [ ]:
F_est = estimate_fundamental_matrix(p_im1,p_im2)

print(' F_est = ',F_est)

# Restrição epipolar para um dos pontos:
test = p_im1h[:,0].T@F_est@p_im2h[:,0]
print('Resultado da restrição epipolar para um ponto usando matriz fundamental estimada:')
print(test)

E_est = estimate_essential_matrix(F_est,fx,fy,ox,oy)

print(E_est)

# Restrição epipolar para um dos pontos:
test = Pc1[:,1].T@E@Pc2[:,1]
print('Resultado da restrição epipolar para um ponto usando matriz essencial estimada:')
print(test)

Pw_reconst_est = estimate_reconstruct_3d(F_est,fx,fy,ox,oy)
print('Reconstrução 3D dos pontos (estimada a menos de fator de escala):')
print(Pw_reconst_est)

## Parte C

In [ ]:
# Traçar as linhas epipolares utilizando F

# Traçar as linhas epipolares utilizando F_est

# Encontrar epipolos utilizando F

# Encontrar epipolos utilizando F_est


## Parte D: Retificação de Imagem (opcional para os alunos da graduação)


### Exercícios

1. Faça a retificação das imagens obtidas pelas duas câmeras de forma que as linhas epipolares fiquem paralelas à horizontal e sejam colineares nas duas imagens. Plote as duas imagens retificadas lado a lado representando a posição de todos os pontos do padrão de calibração nas duas imagens retificadas. Mostre as linhas epipolares para os 7 primeiros pontos do padrão de calibração e verifique que cada par de pontos correspondentes se encontra na mesma coordenada horizontal das imagens retificadas quando colocadas lada a lado.

In [ ]:
# Retificar a imagem da esquerda e mostrar

# Tracar as linhas epipolares na imagem retificada

# Retificar a imagem da direita e mostrar

# Tracar as linhas epipolares na imagem retificada


## Revisão da Parte Teórica

* **Matriz Essencial:**  


$E = S({^l\mathbf{T}}) {^lR_r}$

onde ${^l\mathbf{T}}$ é o vetor que representa a posição da origem da câmera da direita em relação à origem da câmera esquerda, descrito no sistema de coordenadas da câmera da esquerda. ${^lR_r}$ é a orientação da câmera da direita em relação à esquerda.

Para ${^l\mathbf{T}} = [T_x, T_y, T_z]^T$:
\begin{align*}
S({^l\mathbf{T}}) = \begin{bmatrix} -0 &-T_z & T_y \\ T_z &0 &-T_x \\ -T_y &T_x &0 \end{bmatrix}
\end{align*}

Para verificar se a matriz essencial está correta: $\mathbf{P}_l^T E \mathbf{P}_r = 0$

onde $\mathbf{P}_r$ é a coordenada de um ponto 3D descrito no sistema de coordenadas da câmera da direita, e $\mathbf{P}_l$ é a coordenada do mesmo ponto 3D descrito no sistema de coordenadas da câmera da esquerda.

A verificação também pode ser feita utilizando $\mathbf{p}_l^T E \mathbf{p}_r = 0$ para:

$\mathbf{p}_l = \frac{1}{Z_l}\mathbf{P}_l$

$\mathbf{p}_r = \frac{1}{Z_r}\mathbf{P}_r$

ou seja, o ponto $\mathbf{p}$ é a projeção perspectiva de $\mathbf{P}$ em um plano de projeção normalizado (considerando $f=1$).

* **Matriz Fundamental:** $ F = (K_l^{-1})^T E K_r^{-1}$


onde considerou-se a matriz intrínseca:
\begin{align*}
K = \begin{bmatrix} -f/s_x & 0 & o_x \\ 0 & -f/s_y & o_y \\ 0 & 0 &1 \end{bmatrix}
\end{align*}

Observe que para a matriz intrínseca anterior, $\overline{\mathbf{p}} = K \mathbf{p}$, onde $\overline{ \mathbf{p}}$ são as coordenadas em pixel de um ponto no sistema de coordenadas da imagem, e $\mathbf{p}$ são as coordenadas métricas do ponto em um plano de projeção normalizado (com distância focal $f=1$) no sistema de coordenadas da câmera.

Para verificar a matriz fundamental, fazer: $\overline{\mathbf{p}}_l^T F \overline{\mathbf{p}}_r = 0$

## Algumas das Respostas Esperadas

Considerando a câmera 1 como a câmera da esquerda, e a câmera 2 como a câmera da direita:

Matriz Essencial:
```
E =  [[ 122.20948641 -155.20611416 -260.0979196 ]
 [ 177.49733459   36.76649416  117.27625269]
 [ 248.66709046    1.4765014    69.83319781]
```

Matriz Essencial normalizada pelo elemento da linha 3 coluna 3:
```
E =  [[ 1.75001991 -2.22252623 -3.72455978]
 [ 2.54173287  0.5264902   1.67937681]
 [ 3.56087217  0.02114326  1.        ]
 ```


Matriz Fundamental:
```
F =  [[ 8.48676989e-05 -1.07782024e-04  2.13523321e-01]
 [ 1.23262038e-04  2.55322876e-05 -2.11659213e-01]
 [-3.49073957e-01  6.96758286e-02  1.92526380e+02]]
```

Matriz Fundamental normalizada pelo elemento da linha 3 coluna 3:
```
 F =  [[ 4.40810755e-07 -5.59829899e-07  1.10906008e-03]
 [ 6.40234539e-07  1.32617087e-07 -1.09937773e-03]
 [-1.81312274e-03  3.61902762e-04  1.00000000e+00]
 ```